-- AUTO-GENERATED by LuaComponentSchemaRegistry. Do not edit by hand.
-- Source of truth: hob::LuaScriptSystem::bind_components().

local schemas = {
    rigidbody = {
        add = "add_rigidbody",
        setters = {
            body_type = "set_body_type",
            fixed_rotation = "set_fixed_rotation",
        },
    },
    character_body = {
        add = "add_character_body",
        setters = {
            collision_layer = "set_collision_layer",
            collision_mask = "set_collision_mask",
            solver_ignore_mask = "set_solver_ignore_mask",
            capsule = "set_capsule",
        },
    },
    box_collider = {
        add = "add_box_collider",
        setters = {
            aabb = "set_aabb",
            density = "set_density",
            friction = "set_friction",
            bounciness = "set_bounciness",
            collision_layer = "set_collision_layer",
            collision_mask = "set_collision_mask",
            trigger = "set_trigger",
        },
    },
    capsule_collider = {
        add = "add_capsule_collider",
        setters = {
            capsule = "set_capsule",
            density = "set_density",
            friction = "set_friction",
            bounciness = "set_bounciness",
            collision_layer = "set_collision_layer",
            collision_mask = "set_collision_mask",
            trigger = "set_trigger",
        },
    },
    circle_collider = {
        add = "add_circle_collider",
        setters = {
            circle = "set_circle",
            density = "set_density",
            friction = "set_friction",
            bounciness = "set_bounciness",
            collision_layer = "set_collision_layer",
            collision_mask = "set_collision_mask",
            trigger = "set_trigger",
        },
    },
    sprite = {
        add = "add_sprite",
        setters = {
            texture = "set_texture",
            pivot = "set_pivot",
            scale = "set_scale",
            z_index = "set_z_index",
            pixels_per_meter = "set_pixels_per_meter",
            material = "set_material",
        },
    },
    input = {
        add = "add_input",
        setters = {},
    },
    camera = {
        add = "add_camera",
        setters = {
            screen_pixels_per_meter = "set_screen_pixels_per_meter",
        },
    },
}

schemas.__order = {
    "rigidbody",
    "character_body",
    "box_collider",
    "capsule_collider",
    "circle_collider",
    "sprite",
    "input",
    "camera",
}

_G.__component_schemas = schemas
