---@meta
-- AUTO-GENERATED by LuaScriptSystem::dump_component_registry_meta. Do not edit by hand.
-- Source of truth: `DefineComponent.Foo = { ... }` assignments throughout scripts/.
-- Declares the `Components` registry class and adds `---@field` entries so
-- editors autocomplete `Components.Foo`.

---@class Components
---@field Character string
---@field ContactLogger string
---@field Enemy string
---@field EnemyBullet string
---@field EnemySpawner string
---@field Player string
---@field PlayerBullet string
---@field Projectile string
---@field Weapon string
Components = {}
