---@meta
-- AUTO-GENERATED by LuaMetaRegistry. Do not edit by hand.
-- Source of truth: hob::LuaScriptSystem::register_bindings().

-- Math
---@class Math
---@field PI number
---@field EPSILON number
---@field DEG_TO_RAD number
---@field RAD_TO_DEG number
---@field MIN_INTEGER integer
---@field MAX_INTEGER integer
---@field MIN_NUMBER number
---@field MAX_NUMBER number
Math = {}

-- Scripts
---@class Scripts
Scripts = {}

---@param relative_path string
---@return boolean
function Scripts.run_file(relative_path) end

---@param relative_path string
---@param excludes any
---@return boolean
function Scripts.run_folder(relative_path, excludes) end

-- EntitySpawner
---@class EntitySpawner
EntitySpawner = {}

---@return Entity
function EntitySpawner.spawn_entity_c() end

---@param entity Entity
function EntitySpawner.destroy_entity(entity) end

---@param id integer
---@return Entity
function EntitySpawner.get_entity(id) end

-- Input
---@class Input
Input = {}

---@return Vector2
function Input.get_mouse_screen_position() end

-- Timer
---@class Timer
Timer = {}

---@return integer
function Timer.get_fps() end

---@param fps integer
function Timer.set_fps(fps) end

---@return number
function Timer.get_time_scale() end

---@param scale number
function Timer.set_time_scale(scale) end

---@return number
function Timer.get_play_time() end

---@return number
function Timer.get_delta_time() end

-- Assets
---@class Assets
Assets = {}

---@param relative_path string
---@return integer
function Assets.load_texture(relative_path) end

-- Cursor
---@class Cursor
Cursor = {}

---@return integer
function Cursor.get_texture_id() end

---@param texture_id integer
function Cursor.set_texture_id(texture_id) end

---@return Vector2
function Cursor.get_pivot() end

---@param pivot Vector2
function Cursor.set_pivot(pivot) end

---@return Vector2
function Cursor.get_scale() end

---@param scale Vector2
function Cursor.set_scale(scale) end

---@return Color
function Cursor.get_tint() end

---@param tint Color
function Cursor.set_tint(tint) end

---@return boolean
function Cursor.is_visible() end

---@param visible boolean
function Cursor.set_visible(visible) end

-- Camera
---@class Camera
Camera = {}

---@return Entity
function Camera.get_entity() end

---@param world_pos Vector2
---@return Vector2
function Camera.world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function Camera.screen_to_world(screen_pos) end

---@return Vector2
function Camera.get_position() end

---@param position Vector2
function Camera.set_position(position) end

-- Debug
---@class Debug
Debug = {}

---@vararg any
function Debug.log(...) end

---@vararg any
function Debug.log_error(...) end

---@param from Vector2
---@param to Vector2
---@param color Color
---@param thickness number?
function Debug.draw_line(from, to, color, thickness) end

---@param center Vector2
---@param radius number
---@param color Color
---@param thickness number?
---@param segments integer?
function Debug.draw_circle(center, radius, color, thickness, segments) end

-- BodyType
---@enum BodyType
BodyType = {
    Static = 0,
    Dynamic = 1,
    Kinematic = 2,
}

-- InputEventType
---@enum InputEventType
InputEventType = {
    Axis = 0,
    Pressed = 1,
    Released = 2,
}

-- Vector2
---@class Vector2
---@field x number
---@field y number
---@operator add(Vector2): Vector2
---@operator sub(Vector2): Vector2
---@operator unm: Vector2
---@operator mul(number): Vector2
---@operator div(number): Vector2
---@overload fun(): Vector2
---@overload fun(x: number, y: number): Vector2
local Vector2 = {}

---@return number
function Vector2:length() end

---@return number
function Vector2:length_sqr() end

---@return Vector2
function Vector2:normalized() end

---@return Vector2
function Vector2.zero() end

---@return Vector2
function Vector2.one() end

---@return Vector2
function Vector2.left() end

---@return Vector2
function Vector2.right() end

---@return Vector2
function Vector2.up() end

---@return Vector2
function Vector2.down() end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.dot(a, b) end

---@param a Vector2
---@param b Vector2
---@return number
function Vector2.distance(a, b) end

---@param a Vector2
---@param b Vector2
---@param t number
---@return Vector2
function Vector2.lerp(a, b, t) end

---@param point Vector2
---@param pivot Vector2
---@param radians number
---@return Vector2
function Vector2.rotate_around(point, pivot, radians) end

_G.Vector2 = Vector2

-- Capsule
---@class Capsule
---@field center_a Vector2
---@field center_b Vector2
---@field radius number
---@overload fun(center_a: Vector2, center_b: Vector2, radius: number): Capsule
local Capsule = {}

---@return number
function Capsule:get_height() end

_G.Capsule = Capsule

-- AABB
---@class AABB
---@field center Vector2
---@field extents Vector2
---@overload fun(center: Vector2, extents: Vector2): AABB
local AABB = {}

---@return Vector2
function AABB:min() end

---@return Vector2
function AABB:max() end

---@return Vector2
function AABB:size() end

_G.AABB = AABB

-- Color
---@class Color
---@field r number
---@field g number
---@field b number
---@field a number
---@overload fun(): Color
---@overload fun(r: number, g: number, b: number, a: number): Color
local Color = {}

---@return Color
function Color.black() end

---@return Color
function Color.white() end

---@return Color
function Color.gray() end

---@return Color
function Color.red() end

---@return Color
function Color.green() end

---@return Color
function Color.blue() end

---@return Color
function Color.yellow() end

---@return Color
function Color.magenta() end

---@return Color
function Color.cyan() end

---@return Color
function Color.orange() end

_G.Color = Color

-- Entity
---@class Entity
local Entity = {}

---@return integer
function Entity:get_id() end

---@return boolean
function Entity:is_valid() end

---@return boolean
function Entity:is_in_play() end

---@return boolean
function Entity:is_ticking() end

---@param ticking boolean
function Entity:set_ticking(ticking) end

---@return RigidbodyComponent
function Entity:add_rigidbody() end

---@return BoxColliderComponent
function Entity:add_box_collider() end

---@return CapsuleColliderComponent
function Entity:add_capsule_collider() end

---@return CharacterBodyComponent
function Entity:add_character_body() end

---@return SpriteComponent
function Entity:add_sprite() end

---@return InputComponent
function Entity:add_input() end

---@param class_name string
---@return LuaComponent?
function Entity:add_lua_component(class_name) end

---@return TransformComponent
function Entity:get_transform() end

---@return RigidbodyComponent
function Entity:get_rigidbody() end

---@return BoxColliderComponent
function Entity:get_box_collider() end

---@return CapsuleColliderComponent
function Entity:get_capsule_collider() end

---@return CharacterBodyComponent
function Entity:get_character_body() end

---@return SpriteComponent
function Entity:get_sprite() end

---@return InputComponent
function Entity:get_input() end

---@param class_name string
---@return LuaComponent?
function Entity:get_lua_component(class_name) end

---@return LuaComponent[]
function Entity:get_lua_components() end

_G.Entity = Entity

-- Component
---@class Component
local Component = {}

---@return Entity
function Component:get_entity() end

_G.Component = Component

-- TransformComponent
---@class TransformComponent : Component
local TransformComponent = {}

---@return Vector2
function TransformComponent:get_position() end

---@param position Vector2
function TransformComponent:set_position(position) end

---@return number
function TransformComponent:get_rotation() end

---@param radians number
function TransformComponent:set_rotation(radians) end

---@return Vector2
function TransformComponent:get_scale() end

---@param scale Vector2
function TransformComponent:set_scale(scale) end

_G.TransformComponent = TransformComponent

-- SpriteComponent
---@class SpriteComponent : Component
local SpriteComponent = {}

---@return integer
function SpriteComponent:get_texture_id() end

---@param id integer
function SpriteComponent:set_texture_id(id) end

---@return Vector2
function SpriteComponent:get_pivot() end

---@param pivot Vector2
function SpriteComponent:set_pivot(pivot) end

---@return Vector2
function SpriteComponent:get_scale() end

---@param scale Vector2
function SpriteComponent:set_scale(scale) end

---@return Color
function SpriteComponent:get_tint() end

---@param color Color
function SpriteComponent:set_tint(color) end

---@return integer
function SpriteComponent:get_z_index() end

---@param z_index integer
function SpriteComponent:set_z_index(z_index) end

_G.SpriteComponent = SpriteComponent

-- CameraComponent
---@class CameraComponent : Component
local CameraComponent = {}

---@param world_pos Vector2
---@return Vector2
function CameraComponent:world_to_screen(world_pos) end

---@param screen_pos Vector2
---@return Vector2
function CameraComponent:screen_to_world(screen_pos) end

_G.CameraComponent = CameraComponent

-- RigidbodyComponent
---@class RigidbodyComponent : Component
local RigidbodyComponent = {}

---@return BodyType
function RigidbodyComponent:get_body_type() end

---@param body_type BodyType
function RigidbodyComponent:set_body_type(body_type) end

---@return boolean
function RigidbodyComponent:has_fixed_rotation() end

---@param fixed boolean
function RigidbodyComponent:set_fixed_rotation(fixed) end

---@return Vector2
function RigidbodyComponent:get_velocity() end

---@param velocity Vector2
function RigidbodyComponent:set_velocity(velocity) end

---@return Vector2
function RigidbodyComponent:get_position() end

---@param position Vector2
function RigidbodyComponent:set_position(position) end

---@return number
function RigidbodyComponent:get_rotation() end

---@param radians number
function RigidbodyComponent:set_rotation(radians) end

_G.RigidbodyComponent = RigidbodyComponent

-- ColliderComponent
---@class ColliderComponent : Component
local ColliderComponent = {}

---@return number
function ColliderComponent:get_density() end

---@param density number
function ColliderComponent:set_density(density) end

---@return number
function ColliderComponent:get_friction() end

---@param friction number
function ColliderComponent:set_friction(friction) end

---@return number
function ColliderComponent:get_bounciness() end

---@param bounciness number
function ColliderComponent:set_bounciness(bounciness) end

---@return integer
function ColliderComponent:get_collision_layer() end

---@param layer integer
function ColliderComponent:set_collision_layer(layer) end

---@return integer
function ColliderComponent:get_collision_mask() end

---@param mask integer
function ColliderComponent:set_collision_mask(mask) end

---@return boolean
function ColliderComponent:is_trigger() end

---@param trigger boolean
function ColliderComponent:set_trigger(trigger) end

_G.ColliderComponent = ColliderComponent

-- BoxColliderComponent
---@class BoxColliderComponent : ColliderComponent
local BoxColliderComponent = {}

---@return AABB
function BoxColliderComponent:get_aabb() end

---@param aabb AABB
function BoxColliderComponent:set_aabb(aabb) end

_G.BoxColliderComponent = BoxColliderComponent

-- CapsuleColliderComponent
---@class CapsuleColliderComponent : ColliderComponent
local CapsuleColliderComponent = {}

---@return Capsule
function CapsuleColliderComponent:get_capsule() end

---@param capsule Capsule
function CapsuleColliderComponent:set_capsule(capsule) end

_G.CapsuleColliderComponent = CapsuleColliderComponent

-- CharacterBodyComponent
---@class CharacterBodyComponent : Component
local CharacterBodyComponent = {}

---@return integer
function CharacterBodyComponent:get_collision_layer() end

---@param layer integer
function CharacterBodyComponent:set_collision_layer(layer) end

---@return integer
function CharacterBodyComponent:get_collision_mask() end

---@param mask integer
function CharacterBodyComponent:set_collision_mask(mask) end

---@return integer
function CharacterBodyComponent:get_solver_ignore_mask() end

---@param mask integer
function CharacterBodyComponent:set_solver_ignore_mask(mask) end

---@param velocity Vector2
---@param fixed_dt number
function CharacterBodyComponent:move_and_slide(velocity, fixed_dt) end

---@return Vector2
function CharacterBodyComponent:get_velocity() end

---@param velocity Vector2
function CharacterBodyComponent:set_velocity(velocity) end

---@return Vector2
function CharacterBodyComponent:get_position() end

---@param position Vector2
function CharacterBodyComponent:set_position(position) end

---@return number
function CharacterBodyComponent:get_rotation() end

---@param radians number
function CharacterBodyComponent:set_rotation(radians) end

_G.CharacterBodyComponent = CharacterBodyComponent

-- InputComponent
---@class InputComponent : Component
local InputComponent = {}

---@param name string
---@param fn fun(value: number)
---@return integer
function InputComponent:bind_axis(name, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_axis(name, id) end

---@param name string
---@param type InputEventType
---@param fn fun()
---@return integer
function InputComponent:bind_action(name, type, fn) end

---@param name string
---@param id integer
function InputComponent:unbind_action(name, id) end

function InputComponent:clear_all_bindings() end

_G.InputComponent = InputComponent

