#include "lua_factory_schema.h"

#include <fstream>
#include <sstream>

#include "engine/core/logging.h"

namespace hob {
    void LuaFactorySchemaRegistry::add_schema(LuaFactorySchemaInfo info) {
        m_schemas.push_back(std::move(info));
    }

    bool LuaFactorySchemaRegistry::write_to_file(const std::filesystem::path& path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaFactorySchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob:: bind_factory_schema(...) calls in lua_bind_*.cpp.\n\n";

        out << "_G.__factory_schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    " << s.registry_name << " = {\n";
            out << "        define = \"" << s.define_name << "\",\n";
            out << "        lua_type = \"" << s.lua_type << "\",\n";

            if (s.fields.empty()) {
                out << "        fields = {},\n";
            }
            else {
                out << "        fields = {\n";
                for (const auto& f : s.fields) {
                    out << "            { name = \"" << f.name << "\" },\n";
                }
                out << "        },\n";
            }

            out << "    },\n";
        }
        out << "}\n";

        std::error_code ec;
        std::filesystem::create_directories(path.parent_path(), ec);

        std::ofstream f(path, std::ios::binary | std::ios::trunc);
        if (!f) {
            debug::log_error("LuaFactorySchemaRegistry: failed to open '{}' for writing", path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
}
