#include "lua_schema_component.h"

#include <fstream>
#include <sstream>

#include "engine/core/debug.h"

namespace hob {
    void LuaComponentSchemaRegistry::add_schema(std::string key,
                                                std::string add_method,
                                                std::vector<std::pair<std::string, std::string>> setters) {
        m_schemas.push_back({std::move(key), std::move(add_method), std::move(setters)});
    }

    bool LuaComponentSchemaRegistry::write_to_file(const std::filesystem::path& path) const {
        std::ostringstream out;
        out << "-- AUTO-GENERATED by LuaComponentSchemaRegistry. Do not edit by hand.\n";
        out << "-- Source of truth: hob::LuaScriptSystem::bind_components().\n\n";

        out << "local schemas = {\n";
        for (const auto& s : m_schemas) {
            out << "    " << s.key << " = {\n";
            out << "        add = \"" << s.add_method << "\",\n";

            if (s.setters.empty()) {
                out << "        setters = {},\n";
            }
            else {
                out << "        setters = {\n";
                for (const auto& [field, method] : s.setters) {
                    out << "            " << field << " = \"" << method << "\",\n";
                }
                out << "        },\n";
            }

            out << "    },\n";
        }
        out << "}\n\n";

        out << "schemas.__order = {\n";
        for (const auto& s : m_schemas) {
            out << "    \"" << s.key << "\",\n";
        }
        out << "}\n\n";

        out << "_G.__component_schemas = schemas\n";

        std::error_code ec;
        std::filesystem::create_directories(path.parent_path(), ec);

        std::ofstream f(path, std::ios::binary | std::ios::trunc);
        if (!f) {
            debug::log_error("LuaComponentSchemaRegistry: failed to open '{}' for writing", path.string());
            return false;
        }

        const std::string str = out.str();
        f.write(str.data(), static_cast<std::streamsize>(str.size()));

        return f.good();
    }
}
